spring-cloud/spring-cloud-skipper

spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageIndexSynchronizer.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageMetadata.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageSummary.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/repository/PackageMetadataRepository.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/AbstractIntegrationTest.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/AbstractMockMvcTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/index/PackageIndexLoaderTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/repository/PackageMetadataCreator.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/repository/PackageMetadataMvcTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/repository/PackageMetadataRepositoryTests.java

The url `/packageMetadata?projection=summary` gets the summary projection
and contains a link to the full record.
Fixes #11
Fixes #13
Fixes #15
Here is a sample response from the tests:
```
Body = {
"_embedded" : {
"packageMetadata" : [ {
"version" : "1.0.0",
"iconUrl" : null,
"name" : "package1",
"_links" : {
"self" : {
"href" : "http://localhost/packageMetadata/1"
},
"packageMetadata" : {
"href" : "http://localhost/packageMetadata/1{?projection}",
"templated" : true
}
}
}, {
"version" : "2.0.0",
"iconUrl" : null,
"name" : "package2",
"_links" : {
"self" : {
"href" : "http://localhost/packageMetadata/2"
},
"packageMetadata" : {
"href" : "http://localhost/packageMetadata/2{?projection}",
"templated" : true
}
}
} ]
},
"_links" : {
"self" : {
"href" : …
```

Add package summary projection and tests.

---

spring-cloud-skipper-client/pom.xml
spring-cloud-skipper-server/pom.xml

Add dependency in order to generate metadata for classes annotated with
`@ConfigurationProperties`.

Add spring-boot-configuration-processor

---

spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/config/MavenConfigurationProperties.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/config/SkipperServerConfiguration.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/deployer/AppDeployerReleaseManager.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/service/PackageService.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/service/ReleaseService.java
spring-cloud-skipper-server/src/main/resources/application.yml
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/controller/AbstractControllerTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/service/PackageServiceTests.java
spring-cloud-skipper-server/src/test/resources/application-index-test.yml
spring-cloud-skipper-server/src/test/resources/application-repo-test.yml
spring-cloud-skipper-server/src/test/resources/application.yml
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/config/ShellConfiguration.java

* Remove PackageService.loadPackage method, downloadPackage now returns Package
* application.yml for tests specify their own local skipperHome to use local 'target' directory
* Default application.yml specifies spring snapshot repo for maven to simplify development.
* Add ignoring of "origin" in package metadata, going to be implemented correctly in another issue shortly
* Move @ConfigurationProperties for Maven to a top level class
* Do not directly instantiate MavenConfigurationProperties
Fixes #96

Do not use packageMetadata.getOrigin as path when loading packages

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/DefaultSkipperClient.java
spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClient.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/config/SkipperServerProperties.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/controller/PackageController.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageIndexSynchronizer.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/service/PackageService.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/service/ReleaseService.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/service/RepositoryInitializationService.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/controller/AbstractControllerTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/service/ConfigValueUtilsTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/service/PackageServiceTests.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/PackageCommands.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/PackageMetadata.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/PackageUploadProperties.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/Repository.java

- Package service handles uploading of package from the client
- It assumes the client sets the PackageUploadProperties with necessary byte[]
and other attributes such as package name, version and file extension
- Add package upload command that gets the client input
- Retrieves the file content from client file path and sends over to server as byte[] via PackageUploadProperties
- Unpack the file content under the local package Repository location
Resolves #60
```
skipper:>package upload --path file:///Users/igopinatha/workspace/git/ilayaperumalg/spring-cloud-skipper/spring-cloud-skipper-server/packages/ticktock/ticktock-1.0.0.zip
/Users/igopinatha/.skipper/packages/ticktock/ticktock-1.0.0.zip
skipper:>
[igopinatha@mbp ~/.skipper/packages]$ tree
.
└── ticktock
├── ticktock-1.0.0
│   ├── …
```

Add package upload functionality

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/DefaultSkipperClient.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/controller/SkipperController.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/service/PackageMetadataService.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/service/PackageService.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/service/RepositoryInitializationService.java
spring-cloud-skipper-server/src/main/resources/application.yml
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/PackageMetadataDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/service/PackageServiceTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/service/RepositoryInitializationServiceTest.java
spring-cloud-skipper-server/src/test/resources/application-repo-test.yml
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/PackageMetadata.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/Release.java

* When synchronizing package metadata at startup, only attempt
remote repos and if resource exists.  Log failures.
* Add checks to verify the repository to upload exists and is local.
* Add a package repository named "local" to application.yml
* Fix bug setting package metdata to null in Release.setPkg method
* Before returning release objects in controller, explicitly null packageFile
* Update doc tests to not check for packageFileBytes
* Add @JsonIgnore to getter/setter of packageFileBytes in PackageMetadata.
Needed for testing of SCDF stream update command PR
Fixes #170

Refine upgrade support

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/DefaultSkipperClient.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepository.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryTests.java

- Use `findByNameContainingIgnoreCase` instead of `findByNameLike`
Resolves #177

Fix search query in packageMetadata repo

---

spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java
spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/server/controller/RootController.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/RootControllerTests.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ApiDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/AppDeployersDatasDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/DeployersDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/PackageMetadataDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ReleasesDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/controller/docs/RepositoriesDocumentation.java
spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataMvcTests.java
spring-cloud-skipper-server/src/test/resources/application.yml

* Add test
* Add base-path `/api` to `spring-cloud-skipper-server/src/test/resources/application.yml`
- Ensure that all controller tests (incl. documentation) use the `/api` prefix
resolves https://github.com/spring-cloud/spring-cloud-skipper/issues/175

gh-175 Redirect root access to /api

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepository.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryCustom.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryImpl.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/AbstractControllerTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataCreator.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataMvcTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/ReleaseRepositoryTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/RepositoryCreator.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/PackageServiceTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java

- When finding package metadata by name and version, following algorithm is used:
- If there is a single package metadata found, then return
- If there are multiple package metadata, then return the package metadata that belongs to the higher order repository
- If there are no repository order information found, then return the package metadata that has the higher api version
- Add custom repository method in PackageMetadataRepository and RepositoryRepository
- Add tests
Resolves #212

Search package metadata across repositories

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryCustom.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryImpl.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java

- When packageMetadata is queried by the given name, we always throw SkipperException
and hence make this a custom repository method `findByNameRequired`
- Add test
Resolves #256

Use findByNameRequired for packagemetadata by name

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java

- When rolling back, the new rollback release's config was set to the actual release's manifest instead of config values.
- Set the config values instead of manifest
- Update test to check this
Resolves #303

Fix rollback config settings

---

spring-cloud-skipper-client/pom.xml
spring-cloud-skipper/pom.xml

- Fix deps so that client/shell doesn't get any deps
it doesn't need.
- For spring-cloud-skipper, remove all deployer deps and just
use spring-cloud-deployer-spi.
- For spring-cloud-skipper-client, bring back spring-web and httpclient.
Previously httpclient were transitive deps via aether and spring-web via
spring-cloud-deployer-local.
- Fixes #353

Change dependencies leading to shell

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseReportService.java

- Change transaction in ReleaseReportService not to
be read-only which seem to cause error when
postgres is in use.
- Fixes #362

Fix upgrade error with postgres

---

spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/support/SkipperShellApplicationRunner.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/config/ShellConfiguration.java
spring-cloud-skipper-shell-commands/src/main/resources/application.yml

- Add new SkipperShellApplicationRunner handling custom logic
if args are passed in. Fall back to functionality
in DefaultShellApplicationRunner.
- Disable banner as it's annoying when running commands.
- Fixes #360 
```
10:24 $ java -jar spring-cloud-skipper-shell/target/spring-cloud-skipper-shell-1.0.0.BUILD-SNAPSHOT.jar search
╔═════════════════╤═══════╤═══════════════════════════════════════════════════════════════════════════╗
║      Name       │Version│                                Description                                ║
╠═════════════════╪═══════╪═══════════════════════════════════════════════════════════════════════════╣
║helloworld-docker│1.0.0  │The hello world app says hello.                                            ║
║log              │1.1.0  │The log sink uses the …
```

Add support passing shell command args

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClientConfiguration.java
spring-cloud-skipper-client/src/test/java/org/springframework/cloud/skipper/client/SkipperClientConfigurationTests.java

- Rename skipper client default RestTemplate from `restTemplate`
to `skipperClientRestTemplate`. This migitates risks that
any other config magic accidentally overrides the one
we expect.
- Fixes #308

Rename client RestTemplate bean

---

spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/support/InitializeConnectionApplicationRunner.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/support/InteractiveModeApplicationRunner.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/support/ShellUtils.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/config/HelpAwareShellApplicationRunner.java

- Tweak all ApplicationRunner's to understand that when user wants
to print help, we get same output with various options like
-h, -help, --help, help.
- Also change connection init so that if help is requests, we
don't try to connect to a server by changing target. This
removes error if shell is just about to print help.
- We print static usage text and actual shell help command.
- All these happen if commands are run within OS shell,
there's no changes when actual shell instance is launched.
- Didn't add tests as we're still figuring out how proper
e2e tests should get handled.
- Fixes #369 
With these:
```
java -jar spring-cloud-skipper-shell/target/spring-cloud-skipper-shell-1.0.0.BUILD-SNAPSHOT.jar help
java -jar spring-cloud-skipper-shell/target/spring-cloud-skipper-shell-1.0.0.BUILD …
```

Implement better help command feature

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachineConfiguration.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java

- Now using new TransitionConflightPolicy which allows
to define if parent or child transition is choses if those
two conflicts. Root issue is now fixed in statemachine
snapshots which also caused some random behavioral changes
when threads were used.
- Changed assert in test to what is now always expected.
- Fixes #378

Fix error handling in statemachine

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClientResponseErrorHandler.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/PackageController.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/ReleaseController.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/PackageMetadataService.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/PackageCommands.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/PackageDeleteException.java

- Add logic to first check if package belongs to a remote repository, then check releases if necessary.
- Partial fix - unclear why `SkipperErrorAttributes` is not being invoked when `PackageDeleteException` is thrown.
- Not worth it to investigate the root cause now....nor refactor into `@ControllerAdvice`...
Fixes #486

Fix for propagating PackageDeleteException to client

---

pom.xml
spring-cloud-skipper-server-core/pom.xml

- Remove version from server pom and define it
in dep management in parent pom. This makes jar
to have 5.0.5 instead of 3.2.1 from boot.
- Fixes #510

Manage flyway version

---

pom.xml

Currently, K8S ATs are failing on 1.9.x because the deployer fixes for 1.9 compatibility is in 1.3.1.BS. While I was at it, I also switched the local-deployer, but that doesn't really do anything for K8S ATs.
The local build with tests ran successfully.

Switch local and k8s deployer versions to 1.3.1.BS

---

pom.xml

- Match parent pom version with the one
used in spring-cloud-dependencies import.
- Dalston.SR5 is 1.3.7.RELEASE while Dalston.RELEASE is 1.3.1.RELEASE
- Fixes #565 
Here's a diff from fatjar before and after:
```
$ diff /tmp/skipper-dalston-release.out /tmp/skipper-dalston-sr5.out 
59c59
< BOOT-INF/lib/logging-interceptor-3.6.0.jar
---
> BOOT-INF/lib/logging-interceptor-3.8.1.jar
79,80c79,80
< BOOT-INF/lib/okhttp-3.6.0.jar
< BOOT-INF/lib/okio-1.11.0.jar
---
> BOOT-INF/lib/okhttp-3.8.1.jar
> BOOT-INF/lib/okio-1.13.0.jar
110c110
< BOOT-INF/lib/spring-cloud-commons-1.2.0.RELEASE.jar
---
> BOOT-INF/lib/spring-cloud-commons-1.2.5.RELEASE.jar
112,113c112,113
< BOOT-INF/lib/spring-cloud-config-client-1.3.0.RELEASE.jar
< BOOT-INF/lib/spring-cloud-context-1.2.0.RELEASE.jar
---
> …
```

Use matching cloud versions

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/DefaultSkipperClient.java
spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClient.java
spring-cloud-skipper-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/ReleaseController.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HandleHealthCheckStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/SimpleRedBlackUpgradeStrategy.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/UpgradeStrategy.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/ResetVariablesAction.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/RollbackStartAction.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/SkipperStateMachineService.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachineConfiguration.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/UpgradeCancelAction.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/UpgradeDeployTargetAppsAction.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/AbstractIntegrationTest.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/RollbackDocumentation.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/statemachine/StateMachineTests.java
spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/ReleaseCommands.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/RollbackRequest.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/UpgradeRequest.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/support/DurationStyle.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/support/DurationUtils.java
spring-cloud-skipper/src/test/java/org/springframework/cloud/skipper/support/DurationUtilsTests.java

- This commit focus to add better functionality to
handle timeouts during upgrade and rollback.
- We start by adding `timeout-expression` option to both
`release upgrade` and `release rollback`. This expression
is backed by a feature copy of `DurationUtils` and `DurationStyle`
from boot2, which gives nice upgrade path if that time comes.
Behind a scenes these expressions are translated to millis.
- New duration expression takes all sort of strings like, `60s`,
`PT1H`, etc.
- As we need to pass timout with rollback, introduce `RollbackRequest`
and deprecate previous endpoint which only took `releaseName`
and `version`.
- `ReleaseController` now uses `/rollback` to get `RollbackRequest`,
while `/rollback/{name}/{version}` is the old deprecated endpoint.
- Add some new tests to statemachine. …

Enhance timeout handling with rollback and upgrade

---

spring-cloud-skipper-autoconfigure/src/main/java/org/springframework/cloud/skipper/server/autoconfigure/CloudFoundryPlatformAutoConfiguration.java
spring-cloud-skipper-platform-cloudfoundry/src/test/java/org/springframework/cloud/skipper/deployer/CloudFoundryPlatformPropertiesTest.java
spring-cloud-skipper-platform-cloudfoundry/src/test/resources/application-platform-properties.yml
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeployerReleaseManager.java

- Initialize the `appNamePrefix` configuration in CFAppNameGenerator
- Update test
Fix status calcuation when MultistateDeployer has state
- If the app status has `error`, still check if MultiStateDeployer has valid status and consider it
Resolves #619
Resolves #620

Fix CF app name prefix setting

---

spring-cloud-skipper-docs/src/main/asciidoc/command-reference.adoc

- This adds missing sections for repo add/delete, but only
syntax snippets. Command samples for those should be added
together with #632
- Fixes #626

Add syntax sections for all commands

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachinePersistConfiguration.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/statemachine/StateMachinePersistConfigurationTests.java

- Expose SkipUnwantedVariablesFunction to package level
to test it.
- Fix typo in apply function which caused wrong check
for SkipperVariables.ERROR.
- Fixes #658

Fix typo in persist skip function

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachineConfiguration.java

- Instead of using hard coded value, prefer to use
value from `spring.cloud.skipper.server.strategies.healthcheck.sleepInMillis`
as that is documented.
- Fixes #630

Adjust statemachine timer from settings

---

spring-cloud-skipper-docs/src/main/asciidoc/three-hour-tour.adoc

NOTE: I have a feeling that docs should go complete overhaul as just adding something about cf manifest feels a bit awkward and produces slightly unclear docs.
- Polish some doc content in packages section
and separate Spring Cloud Deployer and
Cloud Foundry in its own sections.
- Fixes #635

Update docs for manifest support

---

spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/SpringCloudDeployerApplicationManifestReader.java

- When there is a JSON format issue which results in `RuntimeJSONMappingException`, catch it and log the exception message along with the manifest
Resolves #606

Handle RuntimeJSONMappingException

---

acceptance-tests/spring-cloud-skipper-acceptance-tests/src/test/resources/postgres.yml

- As official image tweaked how env variables are used
to create user and db, need to fix healthcheck
as otherwise container will not come up.
- Fixes #730

Fix postgres image healtcheck

---

spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryManifestApplicationDeployer.java
spring-cloud-skipper-platform-cloudfoundry/src/test/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryManifestApplicationDeployerTests.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeploymentRequestFactory.java

- When returning the resource location for the URL based resources (file://, http:// etc.,)
the resource location should be appended with the `version` as well.
Resolves #743

Fix resource location for URL based resources

---

spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryManifestApplicationDeployer.java
spring-cloud-skipper-platform-cloudfoundry/src/test/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryManifestApplicationDeployerTests.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeploymentRequestFactory.java

- When returning the resource location for the URL based resources (file://, http:// etc.,)
the resource location should be appended with the `version` as well.
Resolves #743
Add test for CFManifestDeployer getResourceLocation

[1.1.x] Fix resource location for URL based resources

---

pom.xml
spring-cloud-skipper-dependencies/pom.xml

- Update pom to Spring Cloud Greenwich.RC1 train, along with spring cloud build 2.1.RC3
- Override the oauth2 configuration imported by spring-cloud-sso to latest alined with boot 2.1.1
Resolves #767

Use Greenwich.RC1 fix OAuth2 conf dependencies

---

pom.xml
spring-cloud-skipper-server-core/pom.xml
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/DataSourceCloudConfig.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java
spring-cloud-skipper-server/pom.xml

Added commit that imports `DataSourceCloudConfig` instead of creating it as a `@Bean`
Fixes #777

Enable configuration on connection pool on PCF - Take 2

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/db2/V1__Initial_Setup.java

- Use same blob size used elsewhere as for some reason
this value has been way too low as given to use
by schema generation tests.
- We simply change value in initial schema as it has been wrong
and schema has been non-functional, there can't be existing users.
- Fixes #819

Fix blob size in state_machine table

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/mysql/V1__Initial_Setup.java

- As mysql don't have a real sequence, initial value
needs to be inserted. This change makes sure that
we only insert value once and that value will be 1.
- Similar fix will also be done on a dataflow side.
- Fixes #815

Fix mysql initial hibernate_sequence value

---

acceptance-tests/build.gradle
acceptance-tests/custom-apps/skipper-server-with-drivers-template1/build.gradle
acceptance-tests/custom-apps/skipper-server-with-drivers-template2/build.gradle
acceptance-tests/custom-apps/skipper-server-with-drivers-template3/build.gradle
acceptance-tests/docker-images/oracle/dockerfiles/12.1.0.2/installPerl.sh
mvnw
mvnw.cmd
pom.xml
spring-cloud-skipper-dependencies/pom.xml
spring-cloud-skipper-docs/pom.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://docs.spring.io/spring-framework/docs/ migrated to:  
https://docs.spring.io/spring-framework/docs/ ([https](https://docs.spring.io/spring-framework/docs/) result 200).
* http://docs.spring.io/spring-shell/docs/current/api/ migrated to:  
https://docs.spring.io/spring-shell/docs/current/api/ ([https](https://docs.spring.io/spring-shell/docs/current/api/) result 200).
* http://stackoverflow.com/questions/18107375/getting-skipping-jacoco-execution-due-to-missing-execution-data-file-upon …

URL Cleanup

---

spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/DeployersDocumentation.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/deployer/metadata/DeployerConfigurationMetadataResolverTests.java

- We still depend on local deployer metadata and
need to change tests to match what's expected.
- Essentially skip what might have in a boot's hint
arrays as it's just noise.
NOTE: this is a fix for local deployer PR https://github.com/spring-cloud/spring-cloud-deployer-local/pull/161 what that gets merged.

Fix changes in a local deployer

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/DefaultSkipperClient.java
spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClient.java
spring-cloud-skipper-client/src/test/java/org/springframework/cloud/skipper/client/DefaultSkipperClientTests.java
spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryReleaseManager.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/ReleaseController.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/ReleaseManager.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/LogsDocumentation.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/LogInfo.java

- LogInfo represents a map of application logs
- key being the application ID
- value being the log value
- Update ReleaseService, ReleaseManager and SkipperClient interfaces to update this
- Update tests
Resolves #887

Add LogInfo domain model to represent release logs

---

spring-cloud-skipper-server-core/src/main/resources/application.yml

- Excluding all cf related connection properties from
api so that those will not get proposed in a
dataflow UI.
- Fixes #899

Exclude cf connection properties

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/DeployerInitializationService.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/config/SkipperServerPlatformConfigurationTests.java

- In case user defined a single platform not named as `default`, it
was duplicated as `default` resulting two platforms. This commit
simply removes this duplication.
- Internally we don't do any dance around platform names so that we'd
silently switch to `default` if only one non `default` exists. This
is because similar check is allready done on a dataflow side and this
switch happens there. In skipper we use these platforms via repository
and it would have added a complex changes to switch these names in
multiple places, essentially doing platform switch in both skipper
and dataflow. It's just better to fail on a skipper side if
non-existing platform is used as that keeps logic simpler.
- Fixes #901

Remove creation of copied default platform

---

spring-cloud-skipper-server-core/src/main/resources/application.yml

- Mvc will handle reactive types using async calls and
default timout how long it waits are currently undefined
in a framework and default value comes from a servlet container
which in case of tomcat is 30000.
- Change this value in spring to 120000 so that we have more
time to wait response as with CF difficult to get everything
out from a platform within 30 secs.

Change mvc default async timeout

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java

- In DefaultReleaseManager we used to cache states by requested deployment id's,
for example `s0-log-v6,s0-time-v6` which would differ per stream. This was chosen
because `MultiStateAppDeployer.statesReactive` takes this same list meaning it
was only natural working cache key. However as `CloudFoundryAppDeployer` is only
user of that interface and it simply requests everything from org/space totally
disregarding used deployement id's, as a short term fix we can just use existing
MultiStateAppDeployer as a cache key(basically objects hashkey aka same instance).

Change MultiStateAppDeployer caching key

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/DeleteStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/DeployAppStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HealthCheckStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/domain/AppDeployerData.java

- Though the `AppDeployerData` is expected to be non-null, we have seen some scenarios where NPEs are thrown when retrieving the AppDeployerData.
Hence, added null check at all the places where `AppDeployerData` is used.
Resolves #957

Avoid NPE in AppDeployerData

---

spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryApplicationManifestUtils.java

- buildpack is changed as buildpacks in a manifest
in a new cf java client.
- You can still set single buildpack but can read
back only multiple ones.
- This commit needs cf deployer which brings in cf 4.9.x

Fix changed cf java client

---

pom.xml
spring-cloud-skipper-server-core/src/main/resources/application.yml

- Add additional 'service' tag with fixed value to allow showing the Skipper metrics in the Spring Boot WF tile: https://vmware.wavefront.com/integration/springboot
- Update the Prometheus RSocket Spring to 1.2.1
Part of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3965

Add a service metrics tag, for Boot WF integration

---

spring-cloud-skipper-server-core/pom.xml
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/DeleteStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HandleHealthCheckStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HealthCheckStep.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/jpa/ReleaseRepository.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/PackageMetadataService.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/UpgradeCheckTargetAppsAction.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/AbstractIntegrationTest.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ServerDependencies.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/deployer/metadata/DeployerConfigurationMetadataResolverTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/ReleaseRepositoryTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java

- Previously with failed update whole replacing release were
deleted which wrongly delete app which weren't modified. Now
simply deleting changed apps. (HandleHealthCheckStep)
- When checking health, check all apps in an replacing release
instead of marking release healthy if one return true. (HealthCheckStep)
- Polish and add more debug.
- Now that failed update works correctly and after that we can
again deploy stream again, one thing is left to another issue which
is an annoying thing that stream is still showing failed as last
status in a history.
- Fixes #966
- Fixes #964
To test, start skipper with 100s timeout as it defaults to 300s
```
--spring.cloud.skipper.server.strategies.healthcheck.timeout-in-millis=100000
```
Do deploy and fail `time` with update by using wrong probe path: …

Fix status after failed update

---

spring-cloud-skipper-platform-kubernetes/pom.xml

- Change from spring-cloud-starter-kubernetes-config
to spring-cloud-starter-kubernetes-fabric8-config.
- Add spring-context-support as issue
spring-cloud/spring-cloud-commons#878
- Fixes #979

Fix k8s config starter

---

pom.xml

The property `${spring-security-oauth2-autoconfigure.version}` is undefined either in this POM or its ancestry, making this dependency management dependency unusable I think.
I suppose it would be useful to align the version of `spring-security-oauth2-autoconfigure` to any other module in `spring-security-oauth2`, so rather than defining another property just used the existing one.

Use ${spring-security-oauth2.version} uniformly.

---

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClientResponseErrorHandler.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/ReleaseController.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/SkipperErrorAttributes.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java
spring-cloud-skipper-server-core/src/main/resources/application.yml
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/ReleaseControllerTests.java
spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/ReleaseUpgradeException.java

- Fix server error message to be included by setting explicit property
- Add ReleaseUpgradeException to handle the exceptions thrown when performing the release upgrade
- Add test
Resolves #997

Fix Skipper exception handling on upgrade

---

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/SkipperFlywayConfigurationCustomizer.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/mysql/MariadbBeforeBaseline.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/mysql/V1__Initial_Setup.java

- Essentially moving existing mysql integration into mariadb
- We target mariadb 10.3+ so for hibernate_sequence use
a real sequence due to hibernate dialect.
- Keep classes in classpath under `mysql` due to
https://github.com/spring-projects/spring-boot/issues/28728
- Fixes #1018

Add proper mariadb support

---

spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryManifestApplicationDeployer.java
spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryReleaseManager.java

Co-authored-by: Moderne <team@moderne.io>

refactor: SLF4J logging statements shouldn't start with `String.format`.

---

spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests.java
spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ConfigValueUtilsTests.java
spring-cloud-skipper/src/test/java/org/springframework/cloud/skipper/io/PackageWriterTests.java

Change CRLF (\r\n) to LF (\n) in tests when comparing files.
Fixes #1034

Change CRLF to LF in tests when comparing files.

---

spring-cloud-skipper-autoconfigure/src/main/resources/META-INF/spring.factories
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/SkipperFlywayConfigurationCustomizer.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/mysql/MysqlBeforeBaseline.java
spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/db/migration/mysql/V1__Initial_Setup.java

* Use FlywayVendorReplacingEnvironmentPostProcessor to replace {vendor} in spring.flyways.locations
* Add back in the MySQL schema
* Use vendor (mysql) not driver in flyway configuration customizer
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/4887
> ⚠️ ⚠️ **depends on** https://github.com/spring-cloud/spring-cloud-dataflow-common/pull/22

Add support for MySQL 5/8 via MariaDB driver

---

spring-cloud-skipper-server-core/pom.xml

- Source: spring-cloud-dataflow/main (1354167b644c651fbe6b6c9f96d0de8c1833c9f4)
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/4791\

Backport "Add hibernate-micrometer to enable Hibernate metrics"

---

spring-cloud-skipper-server-core/src/main/resources/application.yml
spring-cloud-skipper-server-core/src/test/resources/application.yml

- Add `mavenCentral` remote rep
- Edit `springRepo` (`libs-snapshot` -> `/snapshot`)
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5321
**Prove its broken**
- Switch to `/snapshot`
- Clear my local m2 cache for `org/springframework/cloud/stream/app`
- Run SCDF + Skipper locally
- Register bulk kafka/maven apps from SCDF UI
- Create `time | log` stream def
- Deploy `time | log` stream def
- 💥 
**Fix**
- Add mavenCentral remote repo
- Redo the above steps and see that the 💥 goes away

Adjust `maven.remoteRepositories` for Artifactory cutover
