.travis.yml, pom.xml
=> Add travis and codecov integration

spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/controller/PackageInstallController.java, spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageMetadata.java, spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageMetadataResourceProcessor.java, spring-cloud-skipper-server/src/main/java/org/springframework/cloud/skipper/index/PackageSummaryResourceProcessor.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/AbstractMockMvcTests.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/index/PackageIndexDownloaderTests.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/index/PackageIndexLoaderTests.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/repository/PackageMetadataCreator.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/repository/PackageMetadataMvcTests.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/repository/RepositoryCreator.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/service/RepositoryInitializationServiceTest.java, spring-cloud-skipper-server/src/test/resources/repositories/sources/test/log/log-1.0.0/templates/log.yml, spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/Release.java
* Add links to PackageSummary and PackageMetadata for installation
* More test cleanup
Fixes #14
=> Add PackageInstallController

pom.xml, spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/PackageCommands.java
* Make packageId required for deploy command
Fixes #87
=> Better pretty print of package details.  Update to shell snapshots

spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/config/ShellConfiguration.java
=> Handle initial connection failure the same way as in the shell

spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/SkipperCommands.java
=> Update install command options

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java
- This is now applicable to both install and upgrade
- Add test
Resolves #219
=> Use latest package when version not specified

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeployerReleaseManager.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/DeleteStep.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HealthCheckAndDeleteStep.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/SimpleRedBlackUpgradeStrategy.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/UpgradeStrategy.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseAnalyzerTests.java
- Refactor HealthCheckAndDeleteStep
- minor code cleanups
- Fix typos
=> Cleanup doc/code

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryCustom.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryImpl.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseReportService.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java, spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/Info.java
* Move helper method for packageMetadata lookup into PackageMetadataRepository
Fixes GH-273
=> Move the transactional method `createReport` into another class

spring-cloud-skipper-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-skipper-docs/src/main/asciidoc/three-minute-tour.adoc, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerProperties.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseStateUpdateService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/SkipperControllerTests.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/InstallDocumentation.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ListDocumentation.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ManifestDocumentation.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/StatusDocumentation.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/UploadDocumentation.java, spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/SkipperCommands.java
* Add local docs in three minute tour
Fixes #290
=> ReleaseStateUpdateService should be enabled by default

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepository.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/RepositoryInitializationService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/repository/PackageMetadataRepositoryTests.java
=> Improve synchronizePackageMetadata to check for existing data

spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/NonVersionedAbstractEntity.java, spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/Status.java
=> Updated Status so that it does not have optimistic locking

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClientConfiguration.java, spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/SkipperClientProperties.java, spring-cloud-skipper-docs/src/main/asciidoc/three-hour-tour.adoc, spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/support/InitializeConnectionApplicationRunner.java, spring-cloud-skipper-shell-commands/src/main/resources/usage.txt
=> Change SkipperClientProperties uri property to serverUri

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeployerReleaseManager.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ArgumentSanitizer.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests.java, spring-cloud-skipper-server-core/src/test/resources/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests-configpassword.yaml, spring-cloud-skipper-server-core/src/test/resources/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests-configpasswordredacted.yaml, spring-cloud-skipper-server-core/src/test/resources/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests-nopassword.yaml, spring-cloud-skipper-server-core/src/test/resources/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests-password.yaml, spring-cloud-skipper-server-core/src/test/resources/org/springframework/cloud/skipper/server/service/ArgumentSanitizerTests-passwordredacted.yaml
This PR redacts 2 debug messages that dump the YAML to the log.  Are there other spots that this PR doesn't cover?
resolves #229
=> Redacts sensitive info from manifest info in debug messages.

pom.xml
=> Upgrade to statemachine 1.2.8.RC1

pom.xml
Resolves #412
Also resolves spring-cloud/spring-cloud-dataflow#1908.
=> Update spring cloud build to 1.3.7

pom.xml
=> Upgrade to shell 2.0.0.RELEASE

pom.xml
=> Upgrade to statemachine 1.2.8.RC3

pom.xml
=> Upgrade to statemachine 1.2.8.RC4

pom.xml, spring-cloud-skipper-docs/pom.xml, spring-cloud-skipper-platform-cloudfoundry/pom.xml, spring-cloud-skipper-platform-kubernetes/pom.xml, spring-cloud-skipper-server-core/pom.xml, spring-cloud-skipper-server/pom.xml, spring-cloud-skipper-shell-commands/pom.xml, spring-cloud-skipper-shell/pom.xml, spring-cloud-skipper/pom.xml
=> Define dependency versions in parent POM

pom.xml, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachineConfiguration.java
- Small change when a typo was fixed in a state machine.
- Fixes #509
=> Upgrade to statemachine 1.2.8.RELEASE

spring-cloud-skipper/src/main/resources/org/springframework/cloud/skipper/io/generic-template.yml
=> Add quotes to key and values in the generic-template.yml

spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ReleasesDocumentation.java
=> RESTDocs for Releases FindAll

spring-cloud-skipper-docs/src/main/asciidoc/api-guide.adoc, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/PackageMetadataDocumentation.java
- Add RESTDocs test methods
- Update REST api guide to insert the generated snippets
Resolves #450
=> Add package search RESTDocs

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/AppDeployerDataRepository.java
- To silence warning, replace RestResource
to RepositoryRestResource in AppDeployerDataRepository
- Fixes #553
=> Switch to RepositoryRestResource

pom.xml
- Use matching deployer versions.
- spi 1.3.1.RELEASE
- local 1.3.3.RELEASE
- cf 1.3.1.RELEASE
- k8s 1.3.2.RELEASE
=> Update to latest deployer versions

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/RollbackStartAction.java
- When starting the rollback action, update the appropriate status message saying `Rollback underway`
Resolves #500
=> Update rollback message

pom.xml
=> Upgrade to 1.2.10.RELEASE

spring-cloud-skipper-docs/src/main/asciidoc/command-reference.adoc, spring-cloud-skipper-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-skipper-docs/src/main/asciidoc/three-hour-tour.adoc, spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/PackageCommands.java
- Add `package list` as an alias
- Update docs
Resolves #546
=> Make alias for package search cmd

pom.xml
- Change from snapshots to release versions.
- Fixes #603
=> Update local and k8s deployer versions

pom.xml
=> Update to statemachine 1.2.11

acceptance-tests/ci/images/docker-lib.sh, acceptance-tests/ci/images/spring-cloud-skipper-ci-image/Dockerfile, acceptance-tests/ci/parameters.yml, acceptance-tests/ci/pipeline.yml, acceptance-tests/ci/scripts/build-project.sh, acceptance-tests/ci/scripts/build-skipper-server-with-drivers100.sh, acceptance-tests/ci/scripts/build-skipper-server-with-drivers101.sh, acceptance-tests/ci/scripts/build-skipper-server-with-drivers102.sh, acceptance-tests/ci/tasks/build-project.yml, acceptance-tests/ci/tasks/build-skipper-server-with-drivers100.yml, acceptance-tests/ci/tasks/build-skipper-server-with-drivers101.yml, acceptance-tests/ci/tasks/build-skipper-server-with-drivers102.yml
- Make pipeline configuration more configurable to that
it's possible to run it against different branch and repo.
- Fix various issues caused by latest concourse update
which broke the pipeline.
- Fixes #612
- Fixes #613
=> Fix concourse issues

spring-cloud-skipper-docs/src/main/asciidoc/command-reference.adoc, spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/RepositoryCommands.java
- Modify shell and modify docs.
- Fixes #653
=> Remove repo add/delete commands

spring-cloud-skipper/src/main/resources/org/springframework/cloud/skipper/io/generic-template.yml
Should also be added onto master branch
=> Add quotes back to generic-template.yml

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/ServerDependencies.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java
=> Remove use of LRUResourcLoader

spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/PlatformCloudFoundryOperations.java
- Now caching created CloudFoundryOperations per platform name which
should prevent recreation of other cf java client classes and thus
migitates risks of leaking resources.
- Fixes #690
On Linux fd's looked ok with this PR
```
$ jps
1516 spring-cloud-skipper-server-1.1.0.BUILD-SNAPSHOT.jar
jvalkealahti@cypher:~$ ls -lt /proc/1516/fd|wc
107    1169    9054
jvalkealahti@cypher:~$ ls -lt /proc/1516/fd|wc
180    1973   15063
jvalkealahti@cypher:~$ ls -lt /proc/1516/fd|wc
181    1984   15141
jvalkealahti@cypher:~$ ls -lt /proc/1516/fd|wc
180    1973   15063
jvalkealahti@cypher:~$ ls -lt /proc/1516/fd|wc
181    1984   15141
jvalkealahti@cypher:~$ ls -lt /proc/1516/fd|wc
180    1973   15063
```
while previously in my system limit was around 4K
```
jvalkealahti@cypher:~$ ls -lt /proc/14199/fd|wc …
```
=> Prevent CloudFoundryOperations recreate

spring-cloud-skipper-docs/src/main/asciidoc/three-minute-tour.adoc
=> Add examples for CF manifest based deployments

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/DeployerInitializationService.java
=> Fix default deployer account check

spring-cloud-skipper-docs/src/main/asciidoc/command-reference.adoc
=> Document the force!

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/PackageMetadataService.java
=> Log warnings on exceptions when loading package repositories

acceptance-tests/spring-cloud-skipper-acceptance-core/src/test/resources/docker-compose-1.yml, acceptance-tests/spring-cloud-skipper-acceptance-core/src/test/resources/docker-compose-2.yml, acceptance-tests/spring-cloud-skipper-acceptance-core/src/test/resources/docker-compose-3.yml, acceptance-tests/spring-cloud-skipper-acceptance-core/src/test/resources/docker-compose-4.yml, acceptance-tests/spring-cloud-skipper-acceptance-core/src/test/resources/docker-compose-5.yml, acceptance-tests/spring-cloud-skipper-acceptance-core/src/test/resources/docker-compose-6.yml, spring-cloud-skipper-server/Dockerfile
=> Use Ubuntu Bionic as the base image

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerProperties.java
=> Remove unused free disk percentage property

pom.xml, spring-cloud-skipper-server-core/pom.xml, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/DataSourceCloudConfig.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java, spring-cloud-skipper-server/pom.xml
- Registered DataSourceCloudConfig as a bean
- Added logging
- Added connector deps as done in SCDF, verified final jar has same set of deps
Fixes #777
=> Enable configuration on connection pool on PCF

spring-cloud-skipper-server-core/src/main/resources/application.yml
- Fix changed package from org.springframework.boot.context.embedded.tomcat
to org.springframework.boot.web.embedded.tomcat order to log
listen port during startup.
- Fixes #741
=> Change default logging config

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/domain/AppDeployerData.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java
- Inject the app-name, release-name and version into the returned AppInstanceState attributes.
Resolves #801
=> Add AppStatus reference to the original App

README.adoc, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/local/security/OAuth2ServerResource.java, spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/local/security/support/OAuth2TestServer.java
=> Replace "spring.config.location" references with "spring.config.additional-location"

spring-cloud-skipper-docs/src/main/asciidoc/installation.adoc
=> Add doc for CF deployment services

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerProperties.java
=> Remove cf connection pool config from skipper server properties

pom.xml
=> Upgrade to MariaDB connector 2.4.1

etc/checkstyle/checkstyle.xml, pom.xml
- Now rely on versions with latest cloud build 2.1.4.
- Fix some breaking changes with newer versions.
- Fixes #871
=> Fix checkstyle versions

spring-cloud-skipper-server-core/src/main/resources/application.yml
- Assing `ROLE_VIEW` role to the REST endpoint
Resolves #891
=> Secure /api/release/logs/ endpoint

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/SkipperServerConfiguration.java
- Adding @EnableScheduling to a server configuration
so that ReleaseStateUpdateService will get scheduled.
- Fixes #893
=> Fix ReleaseStateUpdateService scheduling

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ReleaseServiceTests.java
- Fix getLog and scale methods on ReleaseService for NPE check on Release
Resolves #906
=> Fix NPE on non existing release

spring-cloud-skipper-docs/src/main/asciidoc/installation.adoc
Related to https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/322
Depends on https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/323
=> Added description of 'autoDeleteMavenArtifacts

spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryReleaseManager.java
=> Add scale operation for CFReleaeManager

spring-cloud-skipper-client/src/main/java/org/springframework/cloud/skipper/client/DefaultSkipperClient.java, spring-cloud-skipper-client/src/test/java/org/springframework/cloud/skipper/client/DefaultSkipperClientTests.java
- Add null checks in DefaultSkipperClient.
- Fixes #925
=> Fix shell NPE

spring-cloud-skipper-server/Dockerfile
=> Update springcloud/openjdk to 2.0.1.RELEASE

spring-cloud-skipper-docs/pom.xml, spring-cloud-skipper-docs/src/main/asciidoc/index.adoc
=> Fix navbar link in Skipper documentation

pom.xml, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/config/security/SkipperOAuthSecurityConfiguration.java
- Conditionally use opaque or jwt token.
- Relates #946
=> Add jwt token support

spring-cloud-skipper-autoconfigure/src/main/java/org/springframework/cloud/skipper/server/autoconfigure/CloudFoundryPlatformAutoConfiguration.java, spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/PlatformCloudFoundryOperations.java, spring-cloud-skipper-platform-cloudfoundry/src/test/java/org/springframework/cloud/skipper/deployer/CloudFoundryPlatformPropertiesTest.java, spring-cloud-skipper-platform-cloudfoundry/src/test/resources/application-platform-properties.yml
=> Configure CF platform connection client id

pom.xml
Resolves https://github.com/spring-cloud/spring-cloud-skipper/issues/961
=> Upgrade fabric8 kubernetes-client

spring-cloud-skipper-docs/src/main/asciidoc/api-guide.adoc, spring-cloud-skipper-docs/src/main/asciidoc/installation.adoc, spring-cloud-skipper-docs/src/main/asciidoc/three-hour-tour.adoc
=> Wording changes

pom.xml, spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/support/PropertiesDiff.java
- Manage hateoas as 1.1.1.RELEASE as it's not yet in boot.
- Change use of generics in DiffBuilder from commons.
- Fixes #951
=> Upgrade to boot 2.3.x

spring-cloud-skipper-server/pom.xml
Addresses https://github.com/spring-cloud/spring-cloud-dataflow/issues/3507
=> Change to use Java 11.0.8 base image

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeploymentRequestFactory.java
Relates to: https://github.com/spring-cloud/spring-cloud-skipper/issues/953
=> Add property to deployment props that represents the unversioned application name

spring-cloud-skipper-docs/src/main/asciidoc/installation.adoc
=> Replace Kuberenetes by Kubernetes

spring-cloud-skipper-server-core/pom.xml, spring-cloud-skipper-server/pom.xml
Fixes #1040. Depends on https://github.com/spring-cloud/spring-cloud-dataflow-build/pull/72 . Related to https://github.com/spring-cloud/spring-cloud-dataflow/pull/4877
=> Add Oracle jdbc dependencies

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/DefaultReleaseManager.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java
=> Added logging

spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseReportService.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/util/ConfigValueUtils.java, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/util/ManifestUtils.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/PackageServiceTests.java, spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/templates/PackageTemplateTests.java, spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/support/YmlUtils.java, spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/CloudFoundryApplicationManifestReader.java, spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/SpringCloudDeployerApplicationManifestReader.java, spring-cloud-skipper/src/test/java/org/springframework/cloud/skipper/io/PackageReaderTests.java
=> Use SafeConstuctor with SnakeYaml

spring-cloud-skipper-server-core/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5057
cc: @cppwfs @corneil @jvalkeal @markpollack
=> Remove Oracle and DB2 drivers

spring-cloud-skipper-docs/src/main/asciidoc/getting-started.adoc, spring-cloud-skipper-docs/src/main/asciidoc/preface.adoc, spring-cloud-skipper-docs/src/main/asciidoc/three-hour-tour.adoc
=> Updated ref docs

spring-cloud-skipper-autoconfigure/src/main/resources/META-INF/spring.factories
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5164
=> Convert Flyway vendor replacer from EPP to ACI

.github/settings.xml, .settings.xml, pom.xml, spring-cloud-skipper-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
=> Add MavenCentral in place of repo.spring.io/release (#101)

.settings.xml, local/download-app.sh, pom.xml, spring-cloud-skipper-dependencies/pom.xml, spring-cloud-skipper-docs/pom.xml, spring-cloud-skipper-docs/src/main/asciidoc/appendix-building.adoc, spring-cloud-skipper-docs/src/main/asciidoc/three-hour-tour.adoc, spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/AboutController.java
See spring-cloud/spring-cloud-dataflow#5325
=> Switch Maven repos off of libs-* variants
